language: go
sudo: false
go:
    - 1.7
before_install: ./scripts/hack/symlink-gopath-travisci
install:
    - go get golang.org/x/tools/cover
    - go get golang.org/x/tools/cmd/cover
script:
    - make gotest
